### ISSUE TITLE
Implement a user-defined rules language

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#11]
- [x] Develop a format for rules description
  - possibly YAML-based
- [ ] Develop an initial version of user-defined rules language
- [ ] Implement tests

## Example

```yaml
rules:
  - name: Rule 6
    description: "Accessing an α-binding"
    pattern: |
      ⟦ ?a ↦ ?n, ?B ⟧.?a
    result: |
      ?n(ρ ↦ ?B)
    when:
      - nf: [ "?n" ]
```
